module.exports = {
  serviecPath:'http://139.196.32.78',
  barTitle: {
    RecommendSongs: '每日推荐',
    R1d:'主题详情',
    Rank: '排行榜',
    HotSong:'热歌榜',
    SongsResource:'歌单',
    Music0:'云音乐新歌榜',
    Music1:'云音乐热歌榜',
    Music2:'网易原创歌曲榜',
    Music4:'云音乐电音榜',
    Music5:'UK排行榜周榜',
    Music6:'美国Billboard周榜',
    Music7:'KTV嗨榜',
    Music8:'iTunes榜',
    Music9:'Hit FM Top榜',
    Music10:'日本Oricon周榜',
    Music11:'韩国Melon排行榜周榜',
    Music12:'韩国Mnet排行榜周榜',
    Music13:'韩国Melon原声周榜',
    Music14:'中国TOP排行榜(港台榜)',
    Music15:'中国TOP排行榜(内地榜)',
    Music16:'香港电台中文歌曲龙虎榜',
    Music17:'华语金曲榜',
    Music18:'中国嘻哈榜',
    Music19:'法国 NRJ EuroHot 30周榜',
    Music20:'台湾Hito排行榜',
    Music21:'Beatport全球电子舞曲榜',
    SingerInfo:'歌手',
    AlbumInfo:'专辑',
    About:'关于',
    Book: '书籍',
    Music: '音乐',
    Movie: '视频',
    Photo: '美图'
  },
  BgColor: {
    C1: '#F70938',
    C2: 'teal',
    C3: 'green',
    C4: 'indigo',
    C5: 'rgba(0, 0, 0, 0.5)',
    C6: 'rgba(37, 40, 47, .87)'
  }
};
